# Generated by Django 3.2.7 on 2023-04-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
    ]
